name: Tests

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Format
        run: npm run prettier:report

      - name: Lint
        run: npm run lint

      - name: Unit test
        run: npm run test
